apiVersion: v1
kind: Service
metadata:
  name: openvpn-gui-service
spec:
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 943
  selector:
    app: openvpn-server
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: openvpn-upd-service
spec:
  ports:
  - name: openvpn-server
    port: 1194
    protocol: UDP
    targetPort: 1194
  selector:
    app: openvpn-server
  type: LoadBalancer