apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openvpn-server
  name: openvpn-server
  annotations:
    k8s.v1.cni.cncf.io/networks: my-network
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: openvpn-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: openvpn-server
      annotations:
        k8s.v1.cni.cncf.io/networks: my-network
    spec:
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1004"
        - name: TZ
          value: Asia/Taipei
        - name: INTERFACE
          value: eth0
        image: ubuntu:20.04
        imagePullPolicy: IfNotPresent
        name: openvpn-server
        command: ["/bin/bash", "-c"]
        args: ['apt update && apt -y install ca-certificates wget net-tools gnupg systemctl && wget -qO - https://as-repository.openvpn.net/as-repo-public.gpg | apt-key add - && echo "deb http://as-repository.openvpn.net/as/debian focal main">/etc/apt/sources.list.d/openvpn-as-repo.list && apt update && apt -y install openvpn-as && tail -f /dev/null']
        ports:
        - containerPort: 1194
          name: openvpn-server
          protocol: UDP
        - containerPort: 943
          name: port1
          protocol: TCP
        - containerPort: 9443
          name: port2
          protocol: TCP
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/local/openvpn_as
          name: openvpn-data
        - mountPath: /config
          name: configs
      - name: unity-robotics
        image: digitaltwinimages.azurecr.io/robotics-nav2-slam:latest
        ports:
          - containerPort: 80
            name: web
          - containerPort: 10000
            name: tcp-endpoint
          - containerPort: 5900
            name: viewer
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
        imagePullPolicy: "IfNotPresent"
        volumeMounts:
          - mountPath: /dev/shm
            name: cache-volume
        envFrom:
        - configMapRef:
            name: ros2-web-bridge-client-config
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: digital-twin-secret
      volumes:
      - name: openvpn-data
        persistentVolumeClaim:
          claimName: openvpn-server-data-pv-claim
      - name: configs
        persistentVolumeClaim:
          claimName: openvpn-server-pv-claim
      - name: ros2-web-bridge-client-config
        configMap:
          name: ros2-web-bridge-client-config
      - emptyDir:
          medium: Memory
          sizeLimit: 1024Mi
        name: cache-volume