
apiVersion: v1
kind: Service
metadata: 
  name: openvpn-server-tcp-endpoint-service
spec:
  ports:
    - name: tcp-endpoint
      port: 10000
    - name: web
      port: 80
    - name: viewer
      protocol: TCP
      port: 5900
  selector: 
    app: openvpn-server
  type: LoadBalancer