apiVersion: v1
kind: Service
metadata:
  name: openvpn-gui-service
  namespace: openvpn
spec:
  ports:
  - name: http
    port: 443
    protocol: TCP
    targetPort: 943
  selector:
    app: openvpn-server
  type: LoadBalancer