apiVersion: v1
kind: Service
metadata:
  name: openvpn-server-service
  namespace: openvpn
spec:
  ports:
  - name: server
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    app: openvpn-server
  type: ClusterIP