apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: openvpn-server
  name: openvpn-server-data-pv-claim
  namespace: openvpn
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "default"