apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openvpn-server
  name: openvpn-server
  namespace: openvpn
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: openvpn-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: openvpn-server
    spec:
      containers:
      - env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1004"
        - name: TZ
          value: Asia/Taipei
        - name: INTERFACE
          value: eth0
        image: linuxserver/openvpn-as
        imagePullPolicy: IfNotPresent
        name: openvpn-server
        ports:
        - containerPort: 1194
          name: openvpn-server
          protocol: UDP
        - containerPort: 943
          name: port1
          protocol: TCP
        - containerPort: 9443
          name: port2
          protocol: TCP
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/openvpn
          name: openvpn-data
        - mountPath: /config
          name: configs
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: openvpn-data
        persistentVolumeClaim:
          claimName: openvpn-server-data-pv-claim
      - name: configs
        persistentVolumeClaim:
          claimName: openvpn-server-pv-claim