apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: my-network
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipvlan",
      "master": "eth0",
      "mode": "l2",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.0.0/16",
        "rangeStart": "192.168.1.160",
        "rangeEnd": "192.168.1.180",
        "gateway": "192.168.1.1"
      }
    }'
