apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros2-ws-navigation-subscriber-deployment
  labels:
    app: ros2-ws-navigation-subscriber
  annotations:
    k8s.v1.cni.cncf.io/networks: my-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ros2-ws-navigation-subscriber
  template:
    metadata:
      labels:
        app: ros2-ws-navigation-subscriber
      annotations:
        k8s.v1.cni.cncf.io/networks: my-network
    spec:
      containers:
      - name: ws-navigation-subscriber
        image: digitaltwinimages.azurecr.io/digitaltwin-bridge
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
        ports:
          - containerPort: 9191
        volumeMounts:
          - name: ros2-web-bridge-client-config
            mountPath: /config.js
            subPath: config.js
        envFrom:
        - configMapRef:
            name: ros2-web-bridge-client-config
      restartPolicy: Always
      imagePullSecrets:
        - name: digital-twin-secret
      volumes:
        - name: ros2-web-bridge-client-config
          configMap:
            name: ros2-web-bridge-client-config

---

apiVersion: v1
kind: Service
metadata: 
  name: ros2-ws-navigation-subscriber-service
spec:
  ports: 
    - name: express
      port: 9191
      targetPort: 9191
      protocol: TCP
  selector: 
    app: ros2-ws-navigation-subscriber
  type: LoadBalancer