apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros2-webviz-deployment
  labels:
    app: ros2-webviz
  annotations:
    k8s.v1.cni.cncf.io/networks: my-network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ros2-webviz
  template:
    metadata:
      labels:
        app: ros2-webviz
      annotations:
        k8s.v1.cni.cncf.io/networks: my-network
    spec:
      containers:
      - name: webviz
        image: cruise/webviz
        ports:
          - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata: 
  name: ros2-webviz-service
spec:
  ports: 
    - name: web
      port: 80
      targetPort: 8080
      protocol: TCP
  selector: 
    app: ros2-webviz
  type: LoadBalancer
